directories:
  output: build
  buildResources: build
productName: Avatar
appId: Avatar
nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  installerIcon: ./build/icon/logo.ico
  uninstallerIcon: ./build/icon/logo.ico
  installerHeaderIcon: ./build/icon/logo.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Avatar
  include: build/script/installer.nsh
files:
  - filter:
      - dist/electron/**/*
win:
  icon: build/icon/logo.ico
  target:
    - target: nsis
      arch:
        - ia32
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
linux:
  icon: build/icons
publish:
  - provider: generic
    url: 'http://152.136.133.94/avatar/'
electronVersion: 3.1.13
